### PR TITLE
Add support for radius token

### PR DESCRIPTION
**Pull request by yukukotani**
SSIA https://github.com/kuma-ui/kuma-ui/issues/257

### CODE REVIEW

**Review by poteboy — APPROVED** [review]
👍

**Comment by poteboy** [comment]
Looks like we have some conflicts 👀

**Comment by yukukotani** [comment]
@poteboy rebased!

**Review by poteboy — APPROVED** [review]
👍

**Comment by poteboy** [comment]
Looks like the test is still failing

**Comment by yukukotani** [comment]
@poteboy Sorry, fixed: [f99c1f0](https://github.com/kuma-ui/kuma-ui/pull/291/commits/f99c1f0633ccb486a47542d1368bd9a5bd036667)

**Pull request merged**
