### PR TITLE
Update minimum pnpm version in package.json to enable auto-install-peers by default

### PR DESCRIPTION
**Pull request by 5000164**
Ref. #361

`auto-install-peers` is enabled by default starting from pnpm v8.0.0, so I've updated the minimum expected version to 8.

### CODE REVIEW

**Review by poteboy — APPROVED** [review]
Thank you!

**Comment by poteboy** [comment]
@kotarella1110 
Hey, I've got a question. When you [introduced Codesandbox](https://github.com/kuma-ui/kuma-ui/pull/212), you downgraded the pnpm engine to version 7. Was this due to incompatibility with Codesandbox?

**Comment by kotarella1110** [comment]
@poteboy Yes, that's right. In fact, this PR indicates that the Codesandbox CI build is failing because the version of the pnpm engine is v8.

**Comment by poteboy** [comment]
Gotcha.

@5000164 
For the above reason, can you explicitly set auto-install-peers to true in .npmrc, at least for now?

**Comment by yukukotani** [comment]
@kotarella1110 @poteboy I believe https://github.com/kuma-ui/kuma-ui/pull/366 can help this PR

**Comment by yukukotani** [comment]
@5000164 Could you rebase to the main branch? Probably failing CodeSandbox CI will be solved.

**Comment by 5000164** [comment]
Thank you all, I'll do it.

**Comment by 5000164** [comment]
@poteboy 
I've rebased and confirmed that the CI has passed.
Could you review it again?

**Review by poteboy — APPROVED** [review]
Thank you!

**Pull request merged**
